name: Issue Welcome

on:
  issues:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `🎉 Thanks for opening an issue!

🚀 Welcome to 62Days-CodeSprint-WebDev-Challenge.

✅ Wait for assignment.
📖 Read CONTRIBUTING.md.
💻 Happy Coding!`
            })